module.exports = {
  styleMarkdownEditorContainer: {
    display: 'flex',
    height: '480px',
    flexDirection: 'column',
    margin: '2px auto',
    padding: '0',
    border: '1px solid #ddd',
    backgroundColor: '#f7f7f7',
  },
  styleMarkdownEditorHeader: {
    display: 'flex',
    flexDirection: 'column',
    borderBottom: '1px solid #ddd',
    marginLeft: '0px',
    marginRight: '0px',
    minHeight: 'auto',
    justifyContent: 'center',
    position: 'relative',
  },
  styleMarkdownMenu: {
    margin: '5px 0',
    flex: '1',
    display: 'flex',
    position: 'absolute',
    right: '16px',
    top: '0px',
    fontSize: '14px',
  },
  styleMarkdownTextArea: {
    height: '441px',
    width: '100%',
    padding: '8px',
    border: 'none',
    outline: 'none',
    resize: 'none',
  },
  styleMarkdownPreviewArea: {
    height: '441px',
    width: '100%',
    padding: '10px',
    backgroundColor: '#fff',
    border: 'none',
    overflow: 'auto',
  },
  styleMarkdownEditorTabs: {
    border: 'none',
    display: 'flex',
    justifyContent: 'flex-start',
  },
  styleTab: {
    padding: '0px 20px',
    cursor: 'pointer',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    height: '36px',
  },
  styleActiveTab: {
    padding: '0px 20px',
    cursor: 'pointer',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    height: '36px',
    backgroundColor: '#fff',
    border: 'none',
    borderRadius: '0',
  },
};
